[tool.poetry]
name = "app_campze"
version = "0.1.0"
description = "Camp Management System"
authors = ["Jack Mthembu"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"  # Using Python 3.11 for better compatibility
Flask = "2.2.5"
Flask-SQLAlchemy = "3.0.2"
Flask-Login = "0.6.2"
Flask-WTF = "1.1.1"
Flask-Mail = "0.9.1"
Flask-Migrate = "4.0.4"
Flask-CORS = "4.0.0"
SQLAlchemy = "2.0.19"
Werkzeug = "2.2.3"
WTForms = "3.0.1"
pdfkit = "1.0.0"
Pillow = "9.5.0"
python-dotenv = "0.21.1"
mysqlclient = "2.2.4"
email-validator = "2.0.0"
python-dateutil = "2.8.2"
pytz = "2023.3"
bcrypt = "4.0.1"
gunicorn = "20.1.0"
cachetools = "5.3.1"
itsdangerous = "2.1.2"
alembic = "1.11.1"
click = "8.1.7"
Jinja2 = "3.1.2"
MarkupSafe = "2.1.3"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 