name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: ignore::DeprecationWarning
      PIP_NO_CACHE_DIR: "true"
      PIP_DISABLE_PIP_VERSION_CHECK: "true"

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.8"
        architecture: 'x64'
        check-latest: true
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          setup.py
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          default-libmysqlclient-dev \
          build-essential \
          pkg-config \
          wkhtmltopdf \
          unixodbc-dev \
          libjpeg-dev \
          zlib1g-dev \
          python3-setuptools
    
    - name: Verify Python version
      run: |
        python --version
        which python
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --upgrade build
    
    - name: Install in development mode
      run: |
        # Install the package in development mode
        pip install -e .
    
    - name: Verify installations
      run: |
        python -c "import flask; print(f'Flask version: {flask.__version__}')"
        python -c "from PIL import Image; print(f'Pillow version: {Image.__version__}')"
        python -c "import sqlalchemy; print(f'SQLAlchemy version: {sqlalchemy.__version__}')"
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 