name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: ignore::DeprecationWarning
      PIP_NO_CACHE_DIR: "true"
      PIP_DISABLE_PIP_VERSION_CHECK: "true"

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: requirements.txt
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          default-libmysqlclient-dev \
          build-essential \
          pkg-config \
          wkhtmltopdf \
          unixodbc-dev \
          libjpeg-dev \
          zlib1g-dev \
          python3-setuptools
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --upgrade build
    
    - name: Install Pillow separately
      run: python -m pip install Pillow==9.5.0
    
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt --no-deps
        python -m pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 