name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: ignore::DeprecationWarning

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.11"
        architecture: 'x64'
        check-latest: true
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          default-libmysqlclient-dev \
          build-essential \
          pkg-config \
          wkhtmltopdf \
          unixodbc-dev \
          libjpeg-dev \
          zlib1g-dev \
          python3-setuptools
    
    - name: Verify Python version
      run: |
        python --version
        which python
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false
    
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi
    
    - name: Verify installations
      run: |
        python -c "import flask; print(f'Flask version: {flask.__version__}')"
        python -c "from PIL import Image; print(f'Pillow version: {Image.__version__}')"
        python -c "import sqlalchemy; print(f'SQLAlchemy version: {sqlalchemy.__version__}')"
    
    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 